---
title: "Assignment 9/11 forecast"
output: html_notebook
---
```{r}
Sept11Travel.data<-read.csv("D:\\BAD\\Sept11Travel.csv")
Sept11Travel.data


Sept11Travel.ts<-ts(Sept11Travel.data, start = c(1990, 1), end = c(2004, 4), freq = 12)
preSept11Travel.ts <- window(Sept11Travel.ts, start = c(1990, 1), end = c(2001, 9))
postSept11Travel.ts <- window(Sept11Travel.ts, start = c(2001,9), end = c(2004,4))

library("forecast")
```

```{r}
Air.ts<-ts(Sept11Travel.data$Air.RPM..000s. , start = c(1990, 1), end = c(2001, 9), freq = 12)
plot(Air.ts, xlab = "Time", ylab = "Air Travel (in 000s)")

```

```{r}
Rail.ts<-ts(Sept11Travel.data$Rail.PM , start = c(1990, 1), end = c(2001, 9), freq = 12)
plot(Rail.ts, xlab = "Time", ylab = "Rail Travel (in 000s)")
```

```{r}
Car.ts<-ts(Sept11Travel.data$VMT..billions. , start = c(1990, 1), end = c(2001, 9), freq = 12)
plot(Car.ts, xlab = "Time", ylab = "Car Travel (in 000s)")
```

```{r}
par(mfrow = c(2, 1))
Air.lm <- forecast::tslm(Air.ts ~ trend + I(trend^2))
plot(Air.ts, xlab = "Time", ylab = "Air Travel (in 000s)", 
     bty = "l")
lines(Air.lm$fitted, lwd = 2)

```

```{r}
par(mfrow = c(2, 1))
Rail.lm <- forecast::tslm(Rail.ts ~ trend + I(trend^2))
plot(Rail.ts, xlab = "Time", ylab = "Rail Travel (in 000s)", 
     bty = "l")
lines(Rail.lm$fitted, lwd = 2)
```

```{r}
par(mfrow = c(2, 1))
Car.lm <- forecast::tslm(Car.ts ~ trend + I(trend^2))
plot(Car.ts, xlab = "Time", ylab = "Car Travel (in 000s)", 
     bty = "l")
lines(Car.lm$fitted, lwd = 2)
```
```{r}

Air.lm.season <- tslm(Air.ts ~ season)
summary(Air.lm.season)
Air.lm.trend.season <- tslm(Air.ts ~ trend + I(trend^2) + season)
summary(Air.lm.trend.season)
Air.lm.trend.season.pred <- forecast(Air.lm.trend.season, level = 0)

par(mfrow = c(2,1))
plot(Air.lm.trend.season.pred, ylim = c(1300, 2600),  ylab = "Air Travel in(000s)", 
 xlab = "Time", bty = "l", xaxt = "n", xlim = c(1990,2001.25), main = "", flty = 2)
axis(1, at = seq(1990, 2001, 9), labels = format(seq(1990, 2001, 9))) 

lines(Air.lm.trend.season$fitted, lwd = 2)

```

```{r}
Rail.lm.season <- tslm(Rail.ts ~ season)
summary(Rail.lm.season)
Rail.lm.trend.season <- tslm(Rail.ts ~ trend + I(trend^2) + season)
summary(Rail.lm.trend.season)
Rail.lm.trend.season.pred <- forecast(Rail.lm.trend.season, level = 0)

par(mfrow = c(2,1))
plot(Rail.lm.trend.season.pred, ylim = c(1300, 2600),  ylab = "Rail Travel (in 000s)", 
 xlab = "Time", bty = "l", xaxt = "n", xlim = c(1990,2001.25), main = "", flty = 2)
axis(1, at = seq(1990, 2001, 9), labels = format(seq(1990, 2001, 9))) 

lines(Rail.lm.trend.season$fitted, lwd = 2)
```

```{r}
Car.lm.season <- tslm(Car.ts ~ season)
summary(Car.lm.season)
Car.lm.trend.season <- tslm(Car.ts ~ trend + I(trend^2) + season)
summary(Car.lm.trend.season)
Car.lm.trend.season.pred <- forecast(Car.lm.trend.season, level = 0)

par(mfrow = c(2,1))
plot(Car.lm.trend.season.pred, ylim = c(1300, 2600),  ylab = "Car Travel (in 000s)", 
 xlab = "Time", bty = "l", xaxt = "n", xlim = c(1990,2001.25), main = "", flty = 2)
axis(1, at = seq(1990, 2001, 9), labels = format(seq(1990, 2001, 9))) 

lines(Car.lm.trend.season$fitted, lwd = 2)
```


